-- DDL script for table appdata for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:11 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE appdata CASCADE CONSTRAINTS;


CREATE TABLE appdata
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   gadgetdefinitionid NUMBER(19,0),
   personid NUMBER(19,0)
);


-- Primary key

ALTER TABLE appdata ADD  CONSTRAINT appdata_pkey
PRIMARY KEY(id);

EXIT;

