-- Control file for Oracle SQL Loader
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:16 2011

OPTIONS(direct=false)
LOAD DATA
INFILE 'appdatavalue.txt'
INTO TABLE appdatavalue
INSERT
FIELDS TERMINATED BY ',' TRAILING NULLCOLS
(id,
 version,
 name CHAR(255) OPTIONALLY ENCLOSED BY '"',
 VALUE_FILE FILLER OPTIONALLY ENCLOSED BY '"',
 value LOBFILE (VALUE_FILE) TERMINATED BY EOF NULLIF VALUE_FILE='',
 appdataid)
