-- Create a sequence and trigger to implement the identity column
-- For table applicationalertnotification for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:17 2011

-- Create trigger statement

CREATE OR REPLACE TRIGGER swtapplicationalertnotificatio
  BEFORE INSERT ON applicationalertnotification
  REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
when (NEW.id is null)
BEGIN
  SELECT applicationalertnotificationid.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/

EXIT;

