-- Control file for Oracle SQL Loader
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:18 2011

OPTIONS(direct=false)
LOAD DATA
INFILE 'backgrounditem.txt'
INTO TABLE backgrounditem
INSERT
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(id,
 version,
 backgroundtype CHAR(255),
 name)
