-- DDL script for table background_skills for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:20 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE background_skills CASCADE CONSTRAINTS;


CREATE TABLE background_skills
(
   background_id NUMBER(19,0)  NOT NULL,
   backgrounditem_id NUMBER(19,0)  NOT NULL,
   skillsindex NUMBER(10,0)  NOT NULL
);


-- Primary key

ALTER TABLE background_skills ADD  CONSTRAINT background_skills_pkey
PRIMARY KEY(background_id,skillsindex);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE background_skills ADD  CONSTRAINT fk82afc47373c22920
FOREIGN KEY(background_id)
REFERENCES background(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE background_skills ADD  CONSTRAINT fk82afc473dd79fca1
FOREIGN KEY(backgrounditem_id)
REFERENCES backgrounditem(id);


--Foreign key is commented since it is identical to the previous foreign key
--ALTER TABLE public.background_skills ADD  CONSTRAINT fk82afc4732a703d60
-- FOREIGN KEY (backgrounditem_id)
--REFERENCES public.backgrounditem (id)   
---- ON DELETE RESTRICT was removed since such behaviour is default while RESTRICT keyword(s) not supported
--  ON UPDATE RESTRICT


ALTER TABLE background_skills ADD CONSTRAINT backgroundskillsbackgrounditem UNIQUE(backgrounditem_id);

EXIT;

