-- DDL script for table background_affiliations for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:18 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE background_affiliations CASCADE CONSTRAINTS;


CREATE TABLE background_affiliations
(
   background_id NUMBER(19,0)  NOT NULL,
   backgrounditem_id NUMBER(19,0)  NOT NULL,
   affiliationindex NUMBER(10,0)  NOT NULL
);


-- Primary key

ALTER TABLE background_affiliations ADD  CONSTRAINT background_affiliations_pkey
PRIMARY KEY(background_id,affiliationindex);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE background_affiliations ADD  CONSTRAINT fk1ab676f47847b0e1
FOREIGN KEY(background_id)
REFERENCES background(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE background_affiliations ADD  CONSTRAINT fk1ab676f42a703d60
FOREIGN KEY(backgrounditem_id)
REFERENCES backgrounditem(id);


ALTER TABLE background_affiliations ADD CONSTRAINT backgroundaffiliationsbackgrou UNIQUE(backgrounditem_id);

EXIT;

