-- DDL script for table backgrounditem for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:18 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE backgrounditem CASCADE CONSTRAINTS;


CREATE TABLE backgrounditem
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   backgroundtype VARCHAR2(255),
   name VARCHAR2(50)  NOT NULL
);


-- Primary key

ALTER TABLE backgrounditem ADD  CONSTRAINT backgrounditem_pkey
PRIMARY KEY(id);

EXIT;

