-- DDL script for table background for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:17 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE background CASCADE CONSTRAINTS;


CREATE TABLE background
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   personid NUMBER(19,0)
);


-- Primary key

ALTER TABLE background ADD  CONSTRAINT background_pkey
PRIMARY KEY(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE background ADD  CONSTRAINT fk276a314ed5843ec
FOREIGN KEY(personid)
REFERENCES person(id);

EXIT;

