-- DDL script for table background_interests for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:20 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE background_interests CASCADE CONSTRAINTS;


CREATE TABLE background_interests
(
   background_id NUMBER(19,0)  NOT NULL,
   backgrounditem_id NUMBER(19,0)  NOT NULL,
   interestindex NUMBER(10,0)  NOT NULL
);


-- Primary key

ALTER TABLE background_interests ADD  CONSTRAINT background_interests_pkey
PRIMARY KEY(background_id,interestindex);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE background_interests ADD  CONSTRAINT fkcb77c0b87847b0e1
FOREIGN KEY(background_id)
REFERENCES background(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE background_interests ADD  CONSTRAINT fkcb77c0b8dd79fca1
FOREIGN KEY(backgrounditem_id)
REFERENCES backgrounditem(id);


ALTER TABLE background_interests ADD CONSTRAINT backgroundinterestsbackgroundi UNIQUE(backgrounditem_id);

EXIT;

