-- Control file for Oracle SQL Loader
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:21 2011

OPTIONS(direct=false)
LOAD DATA
INFILE 'comment.txt'
INTO TABLE "comment"
INSERT
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(id,
 version,
 body,
 timesent TIMESTAMP "YYYY-MM-DD HH24:MI:SS.FF",
 authorpersonid,
 activityid)
