-- DDL script for table "comment" for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:21 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE "COMMENT1" CASCADE CONSTRAINTS;


CREATE TABLE "COMMENT1"
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   body VARCHAR2(250)  NOT NULL,
   timesent TIMESTAMP(6)  NOT NULL,
   authorpersonid NUMBER(19,0)  NOT NULL,
   activityid NUMBER(19,0)  NOT NULL
);


-- Primary key

ALTER TABLE "COMMENT1" ADD  CONSTRAINT comment_pkey
PRIMARY KEY(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE "COMMENT1" ADD  CONSTRAINT fk9bde863fa72a4ce0
FOREIGN KEY(activityid)
REFERENCES activity(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE "COMMENT1" ADD  CONSTRAINT fk9bde863f8ffcaa77
FOREIGN KEY(authorpersonid)
REFERENCES person(id);

EXIT;

