@echo off
echo Importing function public.createperson to Oracle
rem Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
rem Timestamp: Sun May 01 19:40:49 2011

rem --------------------------------------------------------------

sqlplus eureka_streams/YourekaTent!@SW2_GUILLEMOT @createperson.sql

rem --------------------------------------------------------------


