-- Function definition script public.createperson for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:49 2011

SET DEFINE OFF


----Error - can't convert the following object
----Parser error: line 14 - unexpected token 'INTO'
----Code lines:
----<<<<
----    -- create tab for start page
----    FOR rec IN INSERT INTO tabgroup (version) values (0) RETURNING id LOOP
----        _startPageTabGroupId := rec.id;
---->>>>
----Solution: Try to comment/modify this line and restart the conversion or contact support@ispirer.com

CREATE OR REPLACE FUNCTION public.createperson (_accountid character varying, _firstname character varying, _middlename character varying, _lastname character varying, _email character varying, _opensocialid character varying)
RETURNS void

AS $$
DECLARE
    _startPageTabGroupId BIGINT;
    _profileTabGroupId BIGINT;
    _tabTemplateId BIGINT;
    _streamScopeId BIGINT;
    _personId BIGINT;
    rec RECORD;
BEGIN
    -- create tab for start page
    FOR rec IN INSERT INTO tabgroup (version) values (0) RETURNING id LOOP
        _startPageTabGroupId := rec.id;
    END LOOP;
    FOR rec IN INSERT INTO tabtemplate (version, deleted, tablayout, tabname) VALUES (0, false, 'THREECOLUMN', 'Welcome') RETURNING id LOOP
        _tabTemplateId := rec.id;
    END LOOP;
    INSERT INTO tab (version, deleted, tabindex, tabgroupid, templateid) VALUES (0, false, 0, _startPageTabGroupId, _tabTemplateId);
    
    -- create stream
    FOR rec IN INSERT INTO streamscope (version, scopetype, uniquekey) values (0, 'PERSON', _accountid) RETURNING id LOOP
        _streamScopeId := rec.id;
    END LOOP;
    
    -- create person
    FOR rec IN INSERT INTO person (version, accountid, dateadded, email, firstname, followerscount, followingcount, groupscount, 
            lastname, middlename, opensocialid, preferredname, parentorganizationid, starttabgroupid, 
            updatescount, streamviewhiddenlineindex, streamscopeid, 
            commentable, streampostable, accountlocked)
        VALUES (0, _accountid, now(), _email, _firstname, 0, 0, 0, _lastname, _middlename, _opensocialid, _firstname, 1, 
            _startPageTabGroupId, 0, 3, _streamScopeId, true, true, false) RETURNING id LOOP
        _personId := rec.id;
    END LOOP;

    -- update the stream table with the correct destinationentityid for the newly created user.
    UPDATE streamscope set destinationentityid = _personId where id = _streamScopeId;
    
    -- add views for activity page
    INSERT INTO person_stream (personid, streamid, streamindex) 
    VALUES (_personId, 1, 0), (_personId, 2, 1), (_personId, 3, 2), (_personId, 4, 3);
    
    -- follow self
    INSERT INTO follower (followerid, followingid) VALUES (_personId, _personId);
END;
$$ LANGUAGE PLPGSQL



/

SHOW ERRORS;

EXIT;

