-- DDL script for table dailyusagesummary for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:22 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE dailyusagesummary CASCADE CONSTRAINTS;


CREATE TABLE dailyusagesummary
(
   id NUMBER(19,0)  NOT NULL,
   messagecount NUMBER(19,0)  NOT NULL,
   pageviewcount NUMBER(19,0)  NOT NULL,
   streamcontributorcount NUMBER(19,0)  NOT NULL,
   streamviewcount NUMBER(19,0)  NOT NULL,
   streamviewercount NUMBER(19,0)  NOT NULL,
   uniquevisitorcount NUMBER(19,0)  NOT NULL,
   usagedate DATE  NOT NULL,
   avgactivityresponsetime NUMBER(19,0) DEFAULT 0  NOT NULL,
   isweekday NUMBER(1,0)  NOT NULL
);


-- Primary key

ALTER TABLE dailyusagesummary ADD  CONSTRAINT dailyusagesummary_pkey
PRIMARY KEY(id);


ALTER TABLE dailyusagesummary ADD CONSTRAINT dailyusagesummaryusagedateucon UNIQUE(usagedate);

EXIT;

