-- DDL script for table db_version for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:23 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE db_version CASCADE CONSTRAINTS;


CREATE TABLE db_version
(
   major NUMBER(5,0)  NOT NULL,
   minor NUMBER(5,0)  NOT NULL,
   patch VARCHAR2(5)  NOT NULL,
   scriptname VARCHAR2(50)  NOT NULL,
   description CLOB  NOT NULL,
   "timestamp" TIMESTAMP(6) DEFAULT SYSTIMESTAMP
);


-- Primary key

ALTER TABLE db_version ADD  CONSTRAINT db_version_pkey
PRIMARY KEY(major,minor,patch);

EXIT;

