-- DDL script for table domaingroup for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:23 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE domaingroup CASCADE CONSTRAINTS;


CREATE TABLE domaingroup
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   avatarcropsize NUMBER(10,0),
   avatarcropx NUMBER(10,0),
   avatarcropy NUMBER(10,0),
   avatarid VARCHAR2(255),
   bannerid VARCHAR2(255),
   dateadded TIMESTAMP(6)  NOT NULL,
   followerscount NUMBER(10,0)  NOT NULL,
   description VARCHAR2(250),
   name VARCHAR2(150)  NOT NULL,
   publicgroup NUMBER(1,0)  NOT NULL,
   shortname VARCHAR2(150)  NOT NULL,
   url VARCHAR2(255),
   parentorganizationid NUMBER(19,0),
   updatescount NUMBER(10,0)  NOT NULL,
   themeid NUMBER(19,0),
   overview CLOB,
   ispending NUMBER(1,0),
   createdbyid NUMBER(19,0)  NOT NULL,
   streamscopeid NUMBER(19,0),
   commentable NUMBER(1,0) DEFAULT 1  NOT NULL,
   streampostable NUMBER(1,0) DEFAULT 1  NOT NULL,
   suppresspostnotiftomember NUMBER(1,0) DEFAULT 0  NOT NULL,
   suppresspostnotiftocoordinator NUMBER(1,0) DEFAULT 0  NOT NULL
);


-- Primary key

ALTER TABLE domaingroup ADD  CONSTRAINT domaingroup_pkey
PRIMARY KEY(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE domaingroup ADD  CONSTRAINT fk684e33fb9e7c9612
FOREIGN KEY(parentorganizationid)
REFERENCES organization(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE domaingroup ADD  CONSTRAINT fk684e33fbc9da04a0
FOREIGN KEY(createdbyid)
REFERENCES person(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE domaingroup ADD  CONSTRAINT fk684e33fb336c46dc
FOREIGN KEY(streamscopeid)
REFERENCES streamscope(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE domaingroup ADD  CONSTRAINT fk684e33fbb79fc87
FOREIGN KEY(themeid)
REFERENCES theme(id);


ALTER TABLE domaingroup ADD CONSTRAINT domaingroup_shortname_key UNIQUE(shortname);

EXIT;

