-- DDL script for table enrollment_areasofstudy for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:26 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE enrollment_areasofstudy CASCADE CONSTRAINTS;


CREATE TABLE enrollment_areasofstudy
(
   enrollment_id NUMBER(19,0)  NOT NULL,
   backgrounditem_id NUMBER(19,0)  NOT NULL,
   areasofstudyindex NUMBER(10,0)  NOT NULL
);


-- Primary key

ALTER TABLE enrollment_areasofstudy ADD  CONSTRAINT enrollment_areasofstudy_pkey
PRIMARY KEY(enrollment_id,areasofstudyindex);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE enrollment_areasofstudy ADD  CONSTRAINT fkd8b50b27dd79fca1
FOREIGN KEY(backgrounditem_id)
REFERENCES backgrounditem(id);


--Foreign key is commented since it is identical to the previous foreign key
--ALTER TABLE public.enrollment_areasofstudy ADD  CONSTRAINT fkd8b50b272a703d60
-- FOREIGN KEY (backgrounditem_id)
--REFERENCES public.backgrounditem (id)   
---- ON DELETE RESTRICT was removed since such behaviour is default while RESTRICT keyword(s) not supported
--  ON UPDATE RESTRICT


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE enrollment_areasofstudy ADD  CONSTRAINT fkd8b50b27752c5160
FOREIGN KEY(enrollment_id)
REFERENCES enrollment(id);


ALTER TABLE enrollment_areasofstudy ADD CONSTRAINT enrollmentareasofstudybackgrou UNIQUE(backgrounditem_id);

EXIT;

