-- DDL script for table enrollment_activities for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:25 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE enrollment_activities CASCADE CONSTRAINTS;


CREATE TABLE enrollment_activities
(
   enrollment_id NUMBER(19,0)  NOT NULL,
   backgrounditem_id NUMBER(19,0)  NOT NULL,
   activitiesindex NUMBER(10,0)  NOT NULL
);


-- Primary key

ALTER TABLE enrollment_activities ADD  CONSTRAINT enrollment_activities_pkey
PRIMARY KEY(enrollment_id,activitiesindex);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE enrollment_activities ADD  CONSTRAINT fk789c1008dd79fca1
FOREIGN KEY(backgrounditem_id)
REFERENCES backgrounditem(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE enrollment_activities ADD  CONSTRAINT fk789c1008752c5160
FOREIGN KEY(enrollment_id)
REFERENCES enrollment(id);


ALTER TABLE enrollment_activities ADD CONSTRAINT enrollmentactivitiesbackground UNIQUE(backgrounditem_id);

EXIT;

