-- Control file for Oracle SQL Loader
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:25 2011

OPTIONS(direct=false)
LOAD DATA
INFILE 'enrollment_activities.txt'
INTO TABLE enrollment_activities
INSERT
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(enrollment_id,
 backgrounditem_id,
 activitiesindex)
