-- Control file for Oracle SQL Loader
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:25 2011

OPTIONS(direct=false)
LOAD DATA
INFILE 'enrollment.txt'
INTO TABLE enrollment
INSERT
FIELDS TERMINATED BY ',' TRAILING NULLCOLS
(id,
 version,
 ADDITIONALDETAILS_FILE FILLER OPTIONALLY ENCLOSED BY '"',
 additionaldetails LOBFILE (ADDITIONALDETAILS_FILE) TERMINATED BY EOF,
 datefrom DATE "YYYY-MM-DD",
 dateto DATE "YYYY-MM-DD",
 degree CHAR(255) OPTIONALLY ENCLOSED BY '"',
 personid,
 schoolnameid,
 graddate DATE "YYYY-MM-DD")
