-- DDL script for table enrollment for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:25 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE enrollment CASCADE CONSTRAINTS;


CREATE TABLE enrollment
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   additionaldetails CLOB  NOT NULL,
   datefrom DATE,
   dateto DATE,
   degree VARCHAR2(255)  NOT NULL,
   personid NUMBER(19,0),
   schoolnameid NUMBER(19,0),
   graddate DATE
);


-- Primary key

ALTER TABLE enrollment ADD  CONSTRAINT enrollment_pkey
PRIMARY KEY(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE enrollment ADD  CONSTRAINT fk7dbd3f24aa562d22
FOREIGN KEY(schoolnameid)
REFERENCES backgrounditem(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE enrollment ADD  CONSTRAINT fk7dbd3f24351eb3ab
FOREIGN KEY(personid)
REFERENCES person(id);

EXIT;

