-- Control file for Oracle SQL Loader
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:28 2011

OPTIONS(direct=false)
LOAD DATA
INFILE 'feedreader.txt'
INTO TABLE feedreader
INSERT
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(id,
 dateadded TIMESTAMP "YYYY-MM-DD HH24:MI:SS.FF",
 moduleid CHAR(255),
 opensocialid CHAR(255),
 url CHAR(255),
 feedtitle CHAR(255))
