-- DDL script for table feed for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:28 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE feed CASCADE CONSTRAINTS;


CREATE TABLE feed
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   pending NUMBER(1,0)  NOT NULL,
   updated NUMBER(10,0),
   updatefrequency NUMBER(10,0),
   url VARCHAR2(255)  NOT NULL,
   streampluginid NUMBER(19,0)  NOT NULL,
   title VARCHAR2(255)  NOT NULL,
   lastpostdate TIMESTAMP(6),
   lastseenguid VARCHAR2(255),
   broken NUMBER(1,0)
);


-- Primary key

ALTER TABLE feed ADD  CONSTRAINT feed_pkey
PRIMARY KEY(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE feed ADD  CONSTRAINT feed_plugindef_fkey
FOREIGN KEY(streampluginid)
REFERENCES plugindefinition(id);

EXIT;

