-- DDL script for table feedsubscriber for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:29 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE feedsubscriber CASCADE CONSTRAINTS;


CREATE TABLE feedsubscriber
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   confsettings BLOB,
   entityid NUMBER(19,0)  NOT NULL,
   type VARCHAR2(255)  NOT NULL,
   feedid NUMBER(19,0)  NOT NULL,
   requestorid NUMBER(19,0)  NOT NULL
);


-- Primary key

ALTER TABLE feedsubscriber ADD  CONSTRAINT feedsubscriber_pkey
PRIMARY KEY(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE feedsubscriber ADD  CONSTRAINT fk49f6ec4867b493921
FOREIGN KEY(feedid)
REFERENCES feed(id);


ALTER TABLE feedsubscriber ADD  CONSTRAINT feedsubscriberrequestoridfkey
FOREIGN KEY(requestorid)
REFERENCES person(id)   ON DELETE CASCADE;

EXIT;

