-- DDL script for table follower for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:30 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE follower CASCADE CONSTRAINTS;


CREATE TABLE follower
(
   followerid NUMBER(19,0)  NOT NULL,
   followingid NUMBER(19,0)  NOT NULL
);


-- Primary key

ALTER TABLE follower ADD  CONSTRAINT follower_pkey
PRIMARY KEY(followerid,followingid);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE follower ADD  CONSTRAINT fk15d7843e90f5b78b
FOREIGN KEY(followerid)
REFERENCES person(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE follower ADD  CONSTRAINT fk15d7843e52a2bc28
FOREIGN KEY(followingid)
REFERENCES person(id);

EXIT;

