-- Sequence definition script gadgetdefinition_id_seq for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:49 2011

SET DEFINE OFF

DROP SEQUENCE gadgetdefinition_id_seq;
CREATE SEQUENCE gadgetdefinition_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 26 NOCACHE NOCYCLE;
 

SHOW ERRORS;

EXIT;

