-- DDL script for constraints for table gadgetdefinition for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:11 2011

SET DEFINE OFF

--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE appdata ADD  CONSTRAINT fk33de7d4b938cac5f
FOREIGN KEY(gadgetdefinitionid)
REFERENCES gadgetdefinition(id);

EXIT;

