-- DDL script for table gadgetdefinition for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:11 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE gadgetdefinition CASCADE CONSTRAINTS;


CREATE TABLE gadgetdefinition
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   created TIMESTAMP(6)  NOT NULL,
   url VARCHAR2(255)  NOT NULL,
   uuid VARCHAR2(255)  NOT NULL,
   gadgetcategoryid NUMBER(19,0),
   ownerid NUMBER(19,0),
   showingallery NUMBER(1,0),
   numberofusers NUMBER(10,0),
   gadgettitle VARCHAR2(255)
);


-- Primary key

ALTER TABLE gadgetdefinition ADD  CONSTRAINT gadgetdefinition_pkey
PRIMARY KEY(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE gadgetdefinition ADD  CONSTRAINT fk88047adf1da47e22
FOREIGN KEY(gadgetcategoryid)
REFERENCES galleryitemcategory(id);


ALTER TABLE gadgetdefinition ADD CONSTRAINT gadgetdefinition_uuid_key UNIQUE(uuid);

EXIT;

