-- DDL script for table galleryitemcategory for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:07 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE galleryitemcategory CASCADE CONSTRAINTS;


CREATE TABLE galleryitemcategory
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   galleryitemtype VARCHAR2(255),
   name VARCHAR2(50)  NOT NULL
);


-- Primary key

ALTER TABLE galleryitemcategory ADD  CONSTRAINT galleryitemcategory_pkey
PRIMARY KEY(id);

EXIT;

