-- DDL script for table groupmembershiprequests for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:33 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE groupmembershiprequests CASCADE CONSTRAINTS;


CREATE TABLE groupmembershiprequests
(
   groupid NUMBER(19,0)  NOT NULL,
   personid NUMBER(19,0)  NOT NULL
);


-- Primary key

ALTER TABLE groupmembershiprequests ADD  CONSTRAINT groupmembershiprequests_pkey
PRIMARY KEY(groupid,personid);


ALTER TABLE groupmembershiprequests ADD  CONSTRAINT fk6e2b9e7952f1f398
FOREIGN KEY(groupid)
REFERENCES domaingroup(id)   ON DELETE CASCADE;


ALTER TABLE groupmembershiprequests ADD  CONSTRAINT fk6e2b9e79242a4102
FOREIGN KEY(personid)
REFERENCES person(id)   ON DELETE CASCADE;

EXIT;

