-- DDL script for table group_capability for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:32 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE group_capability CASCADE CONSTRAINTS;


CREATE TABLE group_capability
(
   domaingroupid NUMBER(19,0)  NOT NULL,
   capabilityid NUMBER(19,0)  NOT NULL
);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE group_capability ADD  CONSTRAINT fk6ae8ef18a3e873fb
FOREIGN KEY(capabilityid)
REFERENCES backgrounditem(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE group_capability ADD  CONSTRAINT fk6ae8ef184c93c94b
FOREIGN KEY(domaingroupid)
REFERENCES domaingroup(id);


ALTER TABLE group_capability ADD CONSTRAINT groupcapabilitycapabilityidkey UNIQUE(capabilityid);


ALTER TABLE group_capability ADD CONSTRAINT groupcapabilitydomaingroupidke UNIQUE(domaingroupid,capabilityid);

EXIT;

