-- DDL script for table groupfollower for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:33 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE groupfollower CASCADE CONSTRAINTS;


CREATE TABLE groupfollower
(
   followerid NUMBER(19,0)  NOT NULL,
   followingid NUMBER(19,0)  NOT NULL,
   groupstreamindex NUMBER(10,0),
   receivenewactivitynotification NUMBER(1,0) DEFAULT 1  NOT NULL
);


-- Primary key

ALTER TABLE groupfollower ADD  CONSTRAINT groupfollower_pkey
PRIMARY KEY(followerid,followingid);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE groupfollower ADD  CONSTRAINT fkbbf4bb9db18f0221
FOREIGN KEY(followingid)
REFERENCES domaingroup(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE groupfollower ADD  CONSTRAINT fkbbf4bb9da1ea2a34
FOREIGN KEY(followerid)
REFERENCES person(id);

EXIT;

