-- DDL script for table group_coordinators for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:32 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE group_coordinators CASCADE CONSTRAINTS;


CREATE TABLE group_coordinators
(
   domaingroup_id NUMBER(19,0)  NOT NULL,
   coordinators_id NUMBER(19,0)  NOT NULL
);


-- Primary key

ALTER TABLE group_coordinators ADD  CONSTRAINT group_coordinators_pkey
PRIMARY KEY(domaingroup_id,coordinators_id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE group_coordinators ADD  CONSTRAINT fk2fe875433a791ab3
FOREIGN KEY(domaingroup_id)
REFERENCES domaingroup(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE group_coordinators ADD  CONSTRAINT fk2fe87543a345f853
FOREIGN KEY(coordinators_id)
REFERENCES person(id);

EXIT;

