-- Control file for Oracle SQL Loader
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:33 2011

OPTIONS(direct=false)
LOAD DATA
INFILE 'groupfollower.txt'
INTO TABLE groupfollower
INSERT
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(followerid,
 followingid,
 groupstreamindex,
 receivenewactivitynotification)
