-- DDL script for table hashtag for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:34 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE hashtag CASCADE CONSTRAINTS;


CREATE TABLE hashtag
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   content VARCHAR2(255)
);


-- Primary key

ALTER TABLE hashtag ADD  CONSTRAINT hashtag_pkey
PRIMARY KEY(id);


ALTER TABLE hashtag ADD CONSTRAINT hashtag_content_key UNIQUE(content);

EXIT;

