-- Control file for Oracle SQL Loader
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:34 2011

OPTIONS(direct=false)
LOAD DATA
INFILE 'hashtag.txt'
INTO TABLE hashtag
INSERT
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(id,
 version,
 content CHAR(255))
