-- Control file for Oracle SQL Loader
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:34 2011

OPTIONS(direct=false)
LOAD DATA
INFILE 'image.txt'
INTO TABLE image
INSERT
FIELDS TERMINATED BY ',' TRAILING NULLCOLS
(id,
 version,
 imageidentifier CHAR(255) OPTIONALLY ENCLOSED BY '"',
 IMAGEBLOB_FILE FILLER OPTIONALLY ENCLOSED BY '"',
 imageblob LOBFILE (IMAGEBLOB_FILE) TERMINATED BY EOF)
