-- DDL script for table image for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:34 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE image CASCADE CONSTRAINTS;


CREATE TABLE image
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   imageidentifier VARCHAR2(255)  NOT NULL,
   imageblob BLOB  NOT NULL
);


-- Primary key

ALTER TABLE image ADD  CONSTRAINT image_pkey
PRIMARY KEY(id);

EXIT;

