-- DDL script for table job for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:35 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE job CASCADE CONSTRAINTS;


CREATE TABLE job
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   companyname VARCHAR2(50)  NOT NULL,
   datefrom DATE,
   dateto DATE,
   description CLOB  NOT NULL,
   industry VARCHAR2(255)  NOT NULL,
   title VARCHAR2(50)  NOT NULL,
   personid NUMBER(19,0)
);


-- Primary key

ALTER TABLE job ADD  CONSTRAINT job_pkey
PRIMARY KEY(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE job ADD  CONSTRAINT fk1239d351eb3ab
FOREIGN KEY(personid)
REFERENCES person(id);

EXIT;

