-- DDL script for table likedactivity for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:35 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE likedactivity CASCADE CONSTRAINTS;


CREATE TABLE likedactivity
(
   activityid NUMBER(19,0)  NOT NULL,
   personid NUMBER(19,0)  NOT NULL
);

EXIT;

