-- DDL script for table linkinformation_imageurls for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:36 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE linkinformation_imageurls CASCADE CONSTRAINTS;


CREATE TABLE linkinformation_imageurls
(
   linkinformation_id NUMBER(19,0)  NOT NULL,
   element VARCHAR2(255)
);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE linkinformation_imageurls ADD  CONSTRAINT fkf4d16992476abad2
FOREIGN KEY(linkinformation_id)
REFERENCES linkinformation(id);

EXIT;

