-- Control file for Oracle SQL Loader
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:36 2011

OPTIONS(direct=false)
LOAD DATA
INFILE 'linkinformation_imageurls.txt'
INTO TABLE linkinformation_imageurls
INSERT
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(linkinformation_id,
 element CHAR(255))
