-- DDL script for table linkinformation for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:36 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE linkinformation CASCADE CONSTRAINTS;


CREATE TABLE linkinformation
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   created TIMESTAMP(6),
   description VARCHAR2(255),
   largestimageurl VARCHAR2(255),
   title VARCHAR2(255),
   url VARCHAR2(2048),
   source VARCHAR2(255)
);


-- Primary key

ALTER TABLE linkinformation ADD  CONSTRAINT linkinformation_pkey
PRIMARY KEY(id);

EXIT;

