-- Control file for Oracle SQL Loader
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:36 2011

OPTIONS(direct=false)
LOAD DATA
INFILE 'linkinformation.txt'
INTO TABLE linkinformation
INSERT
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(id,
 version,
 created TIMESTAMP "YYYY-MM-DD HH24:MI:SS.FF",
 description CHAR(255),
 largestimageurl CHAR(255),
 title CHAR(255),
 url CHAR(2048),
 source CHAR(255))
