-- DDL script for table membershipcriteria for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:37 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE membershipcriteria CASCADE CONSTRAINTS;


CREATE TABLE membershipcriteria
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   criteria VARCHAR2(255)  NOT NULL,
   systemsettingsid NUMBER(19,0)
);


-- Primary key

ALTER TABLE membershipcriteria ADD  CONSTRAINT membershipcriteria_pkey
PRIMARY KEY(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE membershipcriteria ADD  CONSTRAINT fk30d3517568a7e2e9
FOREIGN KEY(systemsettingsid)
REFERENCES systemsettings(id);

EXIT;

