-- DDL script for table message for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:38 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE message CASCADE CONSTRAINTS;


CREATE TABLE message
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   body VARCHAR2(250)  NOT NULL,
   recipientid VARCHAR2(255)  NOT NULL,
   recipienttype NUMBER(10,0)  NOT NULL,
   timesent TIMESTAMP(6)  NOT NULL,
   title VARCHAR2(50),
   recipientparentorgid NUMBER(19,0)  NOT NULL,
   senderpersonid NUMBER(19,0)  NOT NULL,
   streamitemid NUMBER(19,0)  NOT NULL,
   attachment CLOB,
   sharedactivityid NUMBER(19,0),
   sharerpersonid NUMBER(19,0)
);


-- Primary key

ALTER TABLE message ADD  CONSTRAINT message_pkey
PRIMARY KEY(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE message ADD  CONSTRAINT fk9c2397e7d9e9c2b5
FOREIGN KEY(recipientparentorgid)
REFERENCES organization(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE message ADD  CONSTRAINT fk9c2397e730953d1e
FOREIGN KEY(sharerpersonid)
REFERENCES person(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE message ADD  CONSTRAINT fk9c2397e789cf9aa4
FOREIGN KEY(streamitemid)
REFERENCES streamitemid(id);

EXIT;

