-- DDL script for table notificationfilterpreference for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:39 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE notiffilterpreference CASCADE CONSTRAINTS;


CREATE TABLE notiffilterpreference
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   notificationcategory VARCHAR2(255),
   notifiertype VARCHAR2(255)  NOT NULL,
   personid NUMBER(19,0)  NOT NULL
);


-- Primary key

ALTER TABLE notiffilterpreference ADD CONSTRAINT notiffilterpreferencepk
PRIMARY KEY(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE notiffilterpreference ADD  CONSTRAINT fk7bc6199e242a4102
FOREIGN KEY(personid)
REFERENCES person(id);

EXIT;

