-- Sequence definition script notificationfilterpreferenceid for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:49 2011

SET DEFINE OFF

DROP SEQUENCE notiffilterpreferenceid;
CREATE SEQUENCE notiffilterpreferenceid INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 NOCACHE NOCYCLE;
 

SHOW ERRORS;

EXIT;

