-- DDL script for table oauthtoken for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:41 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE oauthtoken CASCADE CONSTRAINTS;


CREATE TABLE oauthtoken
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   accesstoken VARCHAR2(255)  NOT NULL,
   ownerid VARCHAR2(255)  NOT NULL,
   tokenexpiremillis NUMBER(19,0),
   tokensecret VARCHAR2(255)  NOT NULL,
   viewerid VARCHAR2(255)  NOT NULL,
   consumerid NUMBER(19,0)
);


-- Primary key

ALTER TABLE oauthtoken ADD  CONSTRAINT oauthtoken_pkey
PRIMARY KEY(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE oauthtoken ADD  CONSTRAINT fk30923da21779c778
FOREIGN KEY(consumerid)
REFERENCES oauthconsumer(id);

EXIT;

