-- DDL script for table oauthconsumer for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:39 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE oauthconsumer CASCADE CONSTRAINTS;


CREATE TABLE oauthconsumer
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   callbackurl VARCHAR2(255),
   consumerkey VARCHAR2(255)  NOT NULL,
   consumersecret VARCHAR2(255)  NOT NULL,
   gadgeturl VARCHAR2(255)  NOT NULL,
   serviceprovidername VARCHAR2(255)  NOT NULL,
   signaturemethod VARCHAR2(255)  NOT NULL,
   title VARCHAR2(255)
);


-- Primary key

ALTER TABLE oauthconsumer ADD  CONSTRAINT oauthconsumer_pkey
PRIMARY KEY(id);

EXIT;

