-- DDL script for table oauthdomainentry for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:40 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE oauthdomainentry CASCADE CONSTRAINTS;


CREATE TABLE oauthdomainentry
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   appid VARCHAR2(255),
   authorized NUMBER(1,0)  NOT NULL,
   callbacktoken VARCHAR2(255),
   callbacktokenattempts NUMBER(10,0)  NOT NULL,
   callbackurl VARCHAR2(255),
   callbackurlsigned NUMBER(1,0)  NOT NULL,
   container VARCHAR2(255)  NOT NULL,
   domain VARCHAR2(255)  NOT NULL,
   issuetime TIMESTAMP(6)  NOT NULL,
   oauthversion VARCHAR2(255)  NOT NULL,
   token VARCHAR2(255)  NOT NULL,
   tokensecret VARCHAR2(255)  NOT NULL,
   type VARCHAR2(255)  NOT NULL,
   userid VARCHAR2(255),
   consumerid NUMBER(19,0)
);


-- Primary key

ALTER TABLE oauthdomainentry ADD  CONSTRAINT oauthdomainentry_pkey
PRIMARY KEY(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE oauthdomainentry ADD  CONSTRAINT fk42d0fef71779c778
FOREIGN KEY(consumerid)
REFERENCES oauthconsumer(id);

EXIT;

