-- Control file for Oracle SQL Loader
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:41 2011

OPTIONS(direct=false)
LOAD DATA
INFILE 'oauthtoken.txt'
INTO TABLE oauthtoken
INSERT
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(id,
 version,
 accesstoken CHAR(255),
 ownerid CHAR(255),
 tokenexpiremillis,
 tokensecret CHAR(255),
 viewerid CHAR(255),
 consumerid)
