-- DDL script for table organization for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:09 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE organization CASCADE CONSTRAINTS;


CREATE TABLE organization
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   avatarid VARCHAR2(255),
   avatarcropsize NUMBER(10,0),
   avatarcropx NUMBER(10,0),
   avatarcropy NUMBER(10,0),
   bannerid VARCHAR2(255),
   descendantemployeecount NUMBER(10,0)  NOT NULL,
   descendantgroupcount NUMBER(10,0)  NOT NULL,
   childorganizationcount NUMBER(10,0)  NOT NULL,
   employeefollowercount NUMBER(10,0)  NOT NULL,
   description VARCHAR2(500),
   name VARCHAR2(150)  NOT NULL,
   overview CLOB,
   shortname VARCHAR2(150)  NOT NULL,
   url VARCHAR2(255),
   parentorganizationid NUMBER(19,0),
   themeid NUMBER(19,0),
   updatescount NUMBER(10,0)  NOT NULL,
   alluserscancreategroups NUMBER(1,0) DEFAULT 1  NOT NULL,
   streamscopeid NUMBER(19,0)
);


-- Primary key

ALTER TABLE organization ADD  CONSTRAINT organization_pkey
PRIMARY KEY(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE organization ADD  CONSTRAINT fk501041539e7c9612
FOREIGN KEY(parentorganizationid)
REFERENCES organization(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE organization ADD  CONSTRAINT fk50104153336c46dc
FOREIGN KEY(streamscopeid)
REFERENCES streamscope(id);


ALTER TABLE organization ADD CONSTRAINT organization_shortname_key UNIQUE(shortname);

EXIT;

