-- DDL script for table organization_capability for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:42 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE organization_capability CASCADE CONSTRAINTS;


CREATE TABLE organization_capability
(
   organizationid NUMBER(19,0)  NOT NULL,
   capabilityid NUMBER(19,0)  NOT NULL
);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE organization_capability ADD  CONSTRAINT fk288013a4f0deb4ba
FOREIGN KEY(capabilityid)
REFERENCES backgrounditem(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE organization_capability ADD  CONSTRAINT fk288013a45a0afee8
FOREIGN KEY(organizationid)
REFERENCES organization(id);


ALTER TABLE organization_capability ADD CONSTRAINT organizationcapabilitycapabili UNIQUE(capabilityid);


ALTER TABLE organization_capability ADD CONSTRAINT organizationcapabilityorganiza UNIQUE(organizationid,capabilityid);

EXIT;

