-- Control file for Oracle SQL Loader
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:42 2011

OPTIONS(direct=false)
LOAD DATA
INFILE 'organization_coordinators.txt'
INTO TABLE organization_coordinators
INSERT
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(organization_id,
 coordinators_id)
