-- DDL script for constraints for table organization for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:09 2011

SET DEFINE OFF

--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE activity ADD  CONSTRAINT fka126572fd32c5e36
FOREIGN KEY(recipientparentorgid)
REFERENCES organization(id);

EXIT;

