-- DDL script for table organization_leaders for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:43 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE organization_leaders CASCADE CONSTRAINTS;


CREATE TABLE organization_leaders
(
   organization_id NUMBER(19,0)  NOT NULL,
   leaders_id NUMBER(19,0)  NOT NULL
);


-- Primary key

ALTER TABLE organization_leaders ADD  CONSTRAINT organization_leaders_pkey
PRIMARY KEY(organization_id,leaders_id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE organization_leaders ADD  CONSTRAINT fka537d97ee05d1901
FOREIGN KEY(organization_id)
REFERENCES organization(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE organization_leaders ADD  CONSTRAINT fka537d97e3a006dac
FOREIGN KEY(leaders_id)
REFERENCES person(id);

EXIT;

