-- Control file for Oracle SQL Loader
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:43 2011

OPTIONS(direct=false)
LOAD DATA
INFILE 'organization_leaders.txt'
INTO TABLE organization_leaders
INSERT
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(organization_id,
 leaders_id)
