-- DDL script for table person for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:12 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE person CASCADE CONSTRAINTS;


CREATE TABLE person
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   accountid VARCHAR2(255)  NOT NULL,
   avatarcropsize NUMBER(10,0),
   avatarcropx NUMBER(10,0),
   avatarcropy NUMBER(10,0),
   avatarid VARCHAR2(255),
   biography CLOB,
   cellphone VARCHAR2(255),
   dateadded TIMESTAMP(6)  NOT NULL,
   email VARCHAR2(255)  NOT NULL,
   fax VARCHAR2(255),
   firstname VARCHAR2(50)  NOT NULL,
   followerscount NUMBER(10,0),
   followingcount NUMBER(10,0),
   groupscount NUMBER(10,0),
   lastname VARCHAR2(50)  NOT NULL,
   location VARCHAR2(255),
   middlename VARCHAR2(50),
   opensocialid VARCHAR2(255),
   overview CLOB,
   preferredname VARCHAR2(255)  NOT NULL,
   jobdescription VARCHAR2(250),
   title VARCHAR2(150),
   workphone VARCHAR2(255),
   parentorganizationid NUMBER(19,0),
   starttabgroupid NUMBER(19,0)  NOT NULL,
   themeid NUMBER(19,0),
   personid NUMBER(19,0),
   updatescount NUMBER(10,0),
   streamviewhiddenlineindex NUMBER(10,0),
   lastacceptedtermsofservice TIMESTAMP(6),
   streamscopeid NUMBER(19,0),
   commentable NUMBER(1,0) DEFAULT 1  NOT NULL,
   streampostable NUMBER(1,0) DEFAULT 1  NOT NULL,
   accountlocked NUMBER(1,0) DEFAULT 0  NOT NULL,
   optoutvideoids CLOB,
   groupstreamhiddenlineindex NUMBER(10,0) DEFAULT 3  NOT NULL,
   additionalproperties BLOB,
   companyname VARCHAR2(50)
);


-- Primary key

ALTER TABLE person ADD  CONSTRAINT person_pkey
PRIMARY KEY(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE person ADD  CONSTRAINT fk8e4887759e7c9612
FOREIGN KEY(parentorganizationid)
REFERENCES organization(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE person ADD  CONSTRAINT fk8e488775a5c6101b
FOREIGN KEY(streamscopeid)
REFERENCES streamscope(id);


--Foreign key is commented since it is identical to the previous foreign key
--ALTER TABLE public.person ADD  CONSTRAINT fk8e488775336c46dc
-- FOREIGN KEY (streamscopeid)
--REFERENCES public.streamscope (id)   
---- ON DELETE RESTRICT was removed since such behaviour is default while RESTRICT keyword(s) not supported
--  ON UPDATE RESTRICT


ALTER TABLE person ADD  CONSTRAINT person_starttabgroupid_fkey
FOREIGN KEY(starttabgroupid)
REFERENCES tabgroup(id);


ALTER TABLE person ADD CONSTRAINT person_accountid_key UNIQUE(accountid);

EXIT;

