-- Control file for Oracle SQL Loader
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:46 2011

OPTIONS(direct=false)
LOAD DATA
INFILE 'person_stream.txt'
INTO TABLE person_stream
INSERT
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(personid,
 streamid,
 streamindex)
