-- DDL script for table person_likedsharedresources for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:44 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE person_likedsharedresources CASCADE CONSTRAINTS;


CREATE TABLE person_likedsharedresources
(
   personid NUMBER(19,0)  NOT NULL,
   sharedresourceid NUMBER(19,0)  NOT NULL
);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE person_likedsharedresources ADD  CONSTRAINT fk7111ca7d242a4102
FOREIGN KEY(personid)
REFERENCES person(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE person_likedsharedresources ADD  CONSTRAINT fk7111ca7d35743b2
FOREIGN KEY(sharedresourceid)
REFERENCES sharedresource(id);


ALTER TABLE person_likedsharedresources ADD CONSTRAINT personlikedsharedresourcespers UNIQUE(personid,sharedresourceid);

EXIT;

