-- DDL script for table person_stream for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:46 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE person_stream CASCADE CONSTRAINTS;


CREATE TABLE person_stream
(
   personid NUMBER(19,0)  NOT NULL,
   streamid NUMBER(19,0)  NOT NULL,
   streamindex NUMBER(10,0)  NOT NULL
);


-- Primary key

ALTER TABLE person_stream ADD  CONSTRAINT person_stream_pkey
PRIMARY KEY(personid,streamid);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE person_stream ADD  CONSTRAINT fkbef553aa242a4102
FOREIGN KEY(personid)
REFERENCES person(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE person_stream ADD  CONSTRAINT fkbef553aa6260196c
FOREIGN KEY(streamid)
REFERENCES stream(id);


-- Unique constraint is commented since it is identical to the previous Primary key
--ALTER TABLE public.person_stream ADD CONSTRAINT person_stream_personid_key UNIQUE (personid, streamid)

EXIT;

