-- DDL script for constraints for table person for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:12 2011

SET DEFINE OFF

--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE appdata ADD  CONSTRAINT fk33de7d4b351eb3ab
FOREIGN KEY(personid)
REFERENCES person(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE gadgetdefinition ADD  CONSTRAINT fk88047adfb4103bca
FOREIGN KEY(ownerid)
REFERENCES person(id);

EXIT;

