-- Control file for Oracle SQL Loader
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:43 2011

OPTIONS(direct=false)
LOAD DATA
INFILE 'persistentlogin.txt'
INTO TABLE persistentlogin
INSERT
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(id,
 version,
 accountid CHAR(255),
 tokenexpirationdate,
 tokenvalue CHAR(255))
