-- DDL script for table plugindefinition for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:27 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE plugindefinition CASCADE CONSTRAINTS;


CREATE TABLE plugindefinition
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   created TIMESTAMP(6)  NOT NULL,
   url VARCHAR2(255)  NOT NULL,
   uuid VARCHAR2(255)  NOT NULL,
   objecttype VARCHAR2(255),
   plugincategoryid NUMBER(19,0),
   ownerid NUMBER(19,0),
   showingallery NUMBER(1,0),
   numberofusers NUMBER(10,0),
   updatefrequency NUMBER(19,0)
);


-- Primary key

ALTER TABLE plugindefinition ADD  CONSTRAINT plugindefinition_pkey
PRIMARY KEY(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE plugindefinition ADD  CONSTRAINT plugindefinition_cat_fkey
FOREIGN KEY(plugincategoryid)
REFERENCES galleryitemcategory(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE plugindefinition ADD  CONSTRAINT plugindefinition_owner_fkey
FOREIGN KEY(ownerid)
REFERENCES person(id);


ALTER TABLE plugindefinition ADD CONSTRAINT plugindefinition_uuid_key UNIQUE(uuid);

EXIT;

