-- Control file for Oracle SQL Loader
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:46 2011

OPTIONS(direct=false)
LOAD DATA
INFILE 'recommendation.txt'
INTO TABLE recommendation
INSERT
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(id,
 version,
 authoropensocialid CHAR(255),
 "date" TIMESTAMP "YYYY-MM-DD HH24:MI:SS.FF",
 subjectopensocialid CHAR(255),
 text CHAR(500))
