-- DDL script for table recommendation for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:46 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE recommendation CASCADE CONSTRAINTS;


CREATE TABLE recommendation
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   authoropensocialid VARCHAR2(255)  NOT NULL,
   "date" TIMESTAMP(6)  NOT NULL,
   subjectopensocialid VARCHAR2(255)  NOT NULL,
   text VARCHAR2(500)  NOT NULL
);


-- Primary key

ALTER TABLE recommendation ADD  CONSTRAINT recommendation_pkey
PRIMARY KEY(id);

EXIT;

