-- Control file for Oracle SQL Loader
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:07 2011

OPTIONS(direct=false)
LOAD DATA
INFILE 'sharedresource.txt'
INTO TABLE sharedresource
INSERT
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(id,
 version,
 uniquekey CHAR(2000),
 streamscopeid)
