-- DDL script for table sharedresource for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:07 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE sharedresource CASCADE CONSTRAINTS;


CREATE TABLE sharedresource
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   uniquekey VARCHAR2(2000)  NOT NULL,
   streamscopeid NUMBER(19,0)  NOT NULL
);


-- Primary key

ALTER TABLE sharedresource ADD  CONSTRAINT sharedresource_pkey
PRIMARY KEY(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE sharedresource ADD  CONSTRAINT fk93856bb3956d52f2
FOREIGN KEY(streamscopeid)
REFERENCES streamscope(id);


ALTER TABLE sharedresource ADD CONSTRAINT key_sharedresource_uniquekey UNIQUE(uniquekey);

EXIT;

