@echo off
echo.
echo Importing database objects to Oracle
rem Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
rem Timestamp: Sun May 01 19:40:49 2011

rem --------------------------------------------------------------
rem How to use this command file:

rem To import all database objects and data run:
rem 	sqlways_all.bat all

rem To import tables without data run:
rem 	sqlways_all.bat table

rem To import data into all tables run:
rem 	sqlways_all.bat import

rem To create indexes for all tables run:
rem 	sqlways_all.bat idx

rem To import all database objects without data run:
rem 	sqlways_all.bat ddl

rem --------------------------------------------------------------
echo Import initialization
call "activity_id_seq.bat"
call "appdata_id_seq.bat"
call "appdatavalue_id_seq.bat"
call "background_id_seq.bat"
call "backgrounditem_id_seq.bat"
call "comment_id_seq.bat"
call "domaingroup_id_seq.bat"
call "enrollment_id_seq.bat"
call "feedreader_id_seq.bat"
call "gadget_id_seq.bat"
call "gadgetdefinition_id_seq.bat"
call "galleryitemcategory_id_seq.bat"
call "job_id_seq.bat"
call "linkinformation_id_seq.bat"
call "membershipcriteria_id_seq.bat"
call "message_id_seq.bat"
call "oauthconsumer_id_seq.bat"
call "oauthdomainentry_id_seq.bat"
call "oauthtoken_id_seq.bat"
call "organization_id_seq.bat"
call "persistentlogin_id_seq.bat"
call "person_id_seq.bat"
call "recommendation_id_seq.bat"
call "streamitemid_id_seq.bat"
call "streamscope_id_seq.bat"
call "systemsettings_id_seq.bat"
call "tab_id_seq.bat"
call "tabgroup_id_seq.bat"
call "tabtemplate_id_seq.bat"
call "theme_id_seq.bat"
call "feed_id_seq.bat"
call "plugindefinition_id_seq.bat"
call "feedsubscriber_id_seq.bat"
call "notificationfilterpreferenceid.bat"
call "applicationalertnotificationid.bat"
call "tutorialvideo_id_seq.bat"
call "image_id_seq.bat"
call "hashtag_id_seq.bat"
call "stream_id_seq.bat"
call "usagemetric_id_seq.bat"
call "sharedresource_id_seq.bat"
call "dailyusagesummary_id_seq.bat"

rem --------------------------------------------------------------
echo Importing tables ordered by referential constraints (65 tables)

call  "streamscope.bat" %1
call  "galleryitemcategory.bat" %1
call  "sharedresource.bat" %1
rem	References: streamscope
call  "activity.bat" %1
rem	References: organization, sharedresource, streamscope
call  "organization.bat" %1
rem	References: streamscope, theme
call  "tabgroup.bat" %1
call  "appdata.bat" %1
rem	References: gadgetdefinition, person
call  "gadgetdefinition.bat" %1
rem	References: galleryitemcategory, person
call  "person.bat" %1
rem	References: organization, streamscope, tabgroup, theme
call  "theme.bat" %1
rem	References: galleryitemcategory, person
call  "appdatavalue.bat" %1
rem	References: appdata
call  "applicationalertnotification.bat" %1
rem	References: person
call  "background.bat" %1
rem	References: person
call  "backgrounditem.bat" %1
call  "background_affiliations.bat" %1
rem	References: background, backgrounditem
call  "background_honors.bat" %1
rem	References: background, backgrounditem
call  "background_interests.bat" %1
rem	References: background, backgrounditem
call  "background_skills.bat" %1
rem	References: background, backgrounditem
call  "comment.bat" %1
rem	References: activity, person
call  "dailyusagesummary.bat" %1
call  "db_version.bat" %1
call  "domaingroup.bat" %1
rem	References: organization, person, streamscope, theme
call  "enrollment.bat" %1
rem	References: backgrounditem, person
call  "enrollment_activities.bat" %1
rem	References: backgrounditem, enrollment
call  "enrollment_areasofstudy.bat" %1
rem	References: backgrounditem, enrollment
call  "plugindefinition.bat" %1
rem	References: galleryitemcategory, person
call  "feed.bat" %1
rem	References: plugindefinition
call  "feedreader.bat" %1
call  "feedsubscriber.bat" %1
rem	References: feed, person
call  "follower.bat" %1
rem	References: person
call  "tabtemplate.bat" %1
call  "gadget.bat" %1
rem	References: gadgetdefinition, person, tabtemplate
call  "group_capability.bat" %1
rem	References: backgrounditem, domaingroup
call  "group_coordinators.bat" %1
rem	References: domaingroup, person
call  "groupfollower.bat" %1
rem	References: domaingroup, person
call  "groupmembershiprequests.bat" %1
rem	References: domaingroup, person
call  "hashtag.bat" %1
call  "image.bat" %1
call  "job.bat" %1
rem	References: person
call  "likedactivity.bat" %1
call  "linkinformation.bat" %1
call  "linkinformation_imageurls.bat" %1
rem	References: linkinformation
call  "systemsettings.bat" %1
call  "membershipcriteria.bat" %1
rem	References: systemsettings
call  "streamitemid.bat" %1
call  "message.bat" %1
rem	References: organization, person, streamitemid
call  "notificationfilterpreference.bat" %1
rem	References: person
call  "oauthconsumer.bat" %1
call  "oauthdomainentry.bat" %1
rem	References: oauthconsumer
call  "oauthtoken.bat" %1
rem	References: oauthconsumer
call  "organization_capability.bat" %1
rem	References: backgrounditem, organization
call  "organization_coordinators.bat" %1
rem	References: organization, person
call  "organization_leaders.bat" %1
rem	References: organization, person
call  "persistentlogin.bat" %1
call  "person_likedsharedresources.bat" %1
rem	References: person, sharedresource
call  "person_relatedorganization.bat" %1
rem	References: organization, person
call  "stream.bat" %1
call  "person_stream.bat" %1
rem	References: person, stream
call  "recommendation.bat" %1
call  "starredactivity.bat" %1
rem	References: activity, person
call  "streamhashtag.bat" %1
rem	References: activity, hashtag
call  "systemsettings_ldapgroups.bat" %1
rem	References: systemsettings
call  "tab.bat" %1
rem	References: tabgroup, tabtemplate
call  "tutorialvideo.bat" %1
call  "usagemetric.bat" %1

rem --------------------------------------------------------------
echo Importing sequences ordered by dependency (43 sequences)

call "streamhashtag_id_seq.bat"

rem --------------------------------------------------------------
echo Importing functions ordered by dependency (1 function)


rem --------------------------------------------------------------
