rem Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
rem Timestamp: Sun May 01 19:40:49 2011


cd "C:\workspaces\EurekaStreams-1.1\eurekastreams-server-oracle\ddl"
SQLWays.exe  /D=PostgreSQL35W /U=eurekastreams /P=eurekastreams /SROW=1 /TARGET=Oracle /TVER=10 /TD=SW2_GUILLEMOT /TU=eureka_streams /TP=YourekaTent! /MIGS=Clean /IMPS=Windows /DIR=C:\workspaces\EurekaStreams-1.1\eurekastreams-server-oracle\ddl\scripts /CDEL=, /R=1000 /INI=sqlways_wzd.ini /PRJF=sqlways.xml /NSTOP /GCMD=sqlways_all.bat /RC /LOG=sqlways.log /RPT=sqlways_report.html
"C:\workspaces\EurekaStreams-1.1\eurekastreams-server-oracle\ddl\scripts\sqlways_all.bat"