-- DDL script for table starredactivity for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:47 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE starredactivity CASCADE CONSTRAINTS;


CREATE TABLE starredactivity
(
   activityid NUMBER(19,0)  NOT NULL,
   personid NUMBER(19,0)  NOT NULL
);


-- Primary key

ALTER TABLE starredactivity ADD  CONSTRAINT starredactivity_pkey
PRIMARY KEY(activityid,personid);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE starredactivity ADD  CONSTRAINT fk8216d90e3e94a88a
FOREIGN KEY(activityid)
REFERENCES activity(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE starredactivity ADD  CONSTRAINT fk8216d90e242a4102
FOREIGN KEY(personid)
REFERENCES person(id);

EXIT;

