-- Control file for Oracle SQL Loader
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:47 2011

OPTIONS(direct=false)
LOAD DATA
INFILE 'starredactivity.txt'
INTO TABLE starredactivity
INSERT
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(activityid,
 personid)
