-- DDL script for table streamscope for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:04 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE streamscope CASCADE CONSTRAINTS;


CREATE TABLE streamscope
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   scopetype VARCHAR2(255)  NOT NULL,
   uniquekey VARCHAR2(2000)  NOT NULL,
   destinationentityid NUMBER(19,0)
);


-- Primary key

ALTER TABLE streamscope ADD  CONSTRAINT streamscope_pkey
PRIMARY KEY(id);

EXIT;

