-- Control file for Oracle SQL Loader
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:47 2011

OPTIONS(direct=false)
LOAD DATA
INFILE 'streamhashtag.txt'
INTO TABLE streamhashtag
INSERT
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(id,
 version,
 activitydate TIMESTAMP "YYYY-MM-DD HH24:MI:SS.FF",
 streamentityuniquekey CHAR(255),
 streamscopetype CHAR(255),
 activityid,
 hashtagid)
