-- DDL script for table stream for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:45 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE stream CASCADE CONSTRAINTS;


CREATE TABLE stream
(
   id NUMBER(19,0)  NOT NULL,
   streamsearchid NUMBER(10,0),
   streamviewid NUMBER(10,0),
   version NUMBER(19,0)  NOT NULL,
   name VARCHAR2(255)  NOT NULL,
   readonly NUMBER(1,0)  NOT NULL,
   request CLOB  NOT NULL
);


-- Primary key

ALTER TABLE stream ADD  CONSTRAINT stream_pkey
PRIMARY KEY(id);

EXIT;

