-- Control file for Oracle SQL Loader
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:04 2011

OPTIONS(direct=false)
LOAD DATA
INFILE 'streamscope.txt'
INTO TABLE streamscope
INSERT
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(id,
 version,
 scopetype CHAR(255),
 uniquekey CHAR(2000),
 destinationentityid)
