-- DDL script for table streamitemid for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:38 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE streamitemid CASCADE CONSTRAINTS;


CREATE TABLE streamitemid
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL
);


-- Primary key

ALTER TABLE streamitemid ADD  CONSTRAINT streamitemid_pkey
PRIMARY KEY(id);

EXIT;

