-- Control file for Oracle SQL Loader
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:48 2011

OPTIONS(direct=false)
LOAD DATA
INFILE 'systemsettings_ldapgroups.txt'
INTO TABLE systemsettings_ldapgroups
INSERT
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(systemsettings_id,
 element CHAR(255))
