-- Control file for Oracle SQL Loader
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:48 2011

OPTIONS(direct=false)
LOAD DATA
INFILE 'tab.txt'
INTO TABLE tab
INSERT
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(id,
 version,
 datedeleted TIMESTAMP "YYYY-MM-DD HH24:MI:SS.FF",
 deleted,
 tabindex,
 tabgroupid,
 templateid)
