-- DDL script for table tab for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:48 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE tab CASCADE CONSTRAINTS;


CREATE TABLE tab
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   datedeleted TIMESTAMP(6),
   deleted NUMBER(1,0)  NOT NULL,
   tabindex NUMBER(10,0),
   tabgroupid NUMBER(19,0),
   templateid NUMBER(19,0)
);


-- Primary key

ALTER TABLE tab ADD  CONSTRAINT tab_pkey
PRIMARY KEY(id);


ALTER TABLE tab ADD  CONSTRAINT tab_tabgroupid_fkey
FOREIGN KEY(tabgroupid)
REFERENCES tabgroup(id)   ON DELETE CASCADE;


ALTER TABLE tab ADD  CONSTRAINT tab_templateid_fkey
FOREIGN KEY(templateid)
REFERENCES tabtemplate(id)   ON DELETE CASCADE;

EXIT;

