@echo off
echo Importing sequence tab_id_seq to Oracle
rem Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
rem Timestamp: Sun May 01 19:40:49 2011

rem --------------------------------------------------------------

sqlplus eureka_streams/YourekaTent!@SW2_GUILLEMOT @tab_id_seq.sql

rem --------------------------------------------------------------


