-- DDL script for table tabtemplate for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:30 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE tabtemplate CASCADE CONSTRAINTS;


CREATE TABLE tabtemplate
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   datedeleted TIMESTAMP(6),
   deleted NUMBER(1,0)  NOT NULL,
   tablayout VARCHAR2(255)  NOT NULL,
   tabname VARCHAR2(16)  NOT NULL,
   type VARCHAR2(255)
);


-- Primary key

ALTER TABLE tabtemplate ADD  CONSTRAINT tabtemplate_pkey
PRIMARY KEY(id);

EXIT;

