-- DDL script for table theme for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:15 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE theme CASCADE CONSTRAINTS;


CREATE TABLE theme
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   bannerid VARCHAR2(255)  NOT NULL,
   created TIMESTAMP(6)  NOT NULL,
   cssfile VARCHAR2(255)  NOT NULL,
   dategenerated TIMESTAMP(6),
   description VARCHAR2(200)  NOT NULL,
   name VARCHAR2(255)  NOT NULL,
   themeurl VARCHAR2(255)  NOT NULL,
   uuid VARCHAR2(255)  NOT NULL,
   themecategoryid NUMBER(19,0),
   ownerid NUMBER(19,0),
   authoremail VARCHAR2(255)  NOT NULL,
   authorname VARCHAR2(255)  NOT NULL,
   numberofusers NUMBER(10,0)
);


-- Primary key

ALTER TABLE theme ADD  CONSTRAINT theme_pkey
PRIMARY KEY(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE theme ADD  CONSTRAINT fk4d085a935d4e75f
FOREIGN KEY(themecategoryid)
REFERENCES galleryitemcategory(id);


--SQLWAYS_EVAL# was removed since such behaviour is default while RESTRICT keyword(s) not supported
ALTER TABLE theme ADD  CONSTRAINT fk4d085a9701f8461
FOREIGN KEY(ownerid)
REFERENCES person(id);


ALTER TABLE theme ADD CONSTRAINT theme_uuid_key UNIQUE(uuid);

EXIT;

