-- Control file for Oracle SQL Loader
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:49 2011

OPTIONS(direct=false)
LOAD DATA
INFILE 'tutorialvideo.txt'
INTO TABLE tutorialvideo
INSERT
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(id,
 version,
 dialogtitle CHAR(255),
 innercontent CHAR(1000),
 innercontenttitle CHAR(255),
 page CHAR(255),
 videoheight,
 videourl CHAR(1000),
 videowidth)
