-- DDL script for table tutorialvideo for Oracle
-- Generated by (c) Ispirer SQLWays 4.0 Build 374 EVALUATION VERSION
-- Timestamp: Sun May 01 19:40:49 2011

-- Create table statement

SET DEFINE OFF


DROP TABLE tutorialvideo CASCADE CONSTRAINTS;


CREATE TABLE tutorialvideo
(
   id NUMBER(19,0)  NOT NULL,
   version NUMBER(19,0)  NOT NULL,
   dialogtitle VARCHAR2(255),
   innercontent VARCHAR2(1000),
   innercontenttitle VARCHAR2(255),
   page VARCHAR2(255)  NOT NULL,
   videoheight NUMBER(10,0),
   videourl VARCHAR2(1000),
   videowidth NUMBER(10,0)
);


-- Primary key

ALTER TABLE tutorialvideo ADD  CONSTRAINT tutorialvideo_pkey
PRIMARY KEY(id);

EXIT;

